### ISSUE TITLE
Shell Script examples

### ISSUE THREAD

**Issue by peepsnet** [google/OctoPrint-TemperatureFailsafe#5]
Can you give an example of the shell scripts that you can run.

Is there a website with examples of commands that can be run from a shell in octoprint??

**Comment by precision** [comment]
There isn't a website with examples.  The reason I left it up to a shell script is because there are so many different ways to control relays.  Personally I call curl to hit the HTTP API on my sonoff relays to turn my printers on/off.

I use the following command.
`curl http://192.168.1.100/cm?cmnd=Power%20off`

But again, some people have relays connected to their Pi's and flip GPIOs, some use Home Assistant, etc.

**Comment by peepsnet** [comment]
I see...

Is there a call I can make to stop printing with the default OctoPrint setup?? To a URL in the WebUI?

**Comment by precision** [comment]
If you check the box "cancel print" it should use the OctoPrint internal API to turn off the print when it triggers, you can enter a NOOP in the shell command, something like "echo shutdown".

If that doesn't work for you, I'd recommend checking out the OctoPrint HTTP API documentation.

**Comment by peepsnet** [comment]
Just leave this here in case another has a question...

This will stop all printing. 
`
curl -H "Content-Type: application/json" -H "X-Api-Key:YOURAPIKEY" -X POST -d  "{ \"command\" : \"M112\" }" http://localhost/api/printer/command
`
